name: intl_utils_fork
version: 2.8.8
description: Fork of intl_utils.

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.0.0
  http: ^1.2.2
  path: ^1.8.0
  yaml: ^3.0.0
  intl: ^0.20.1
  archive: ^4.0.1
  analyzer: ^7.1.0
  dart_style: ^3.0.0
  petitparser: ^6.0.2

dev_dependencies:
  test: ^1.16.0
  lints: ^5.1.0
  mockito: ^5.4.3
  build_runner: ^2.0.6
